version: 2.1

commands:
  setup_github:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "70:1d:2f:c4:ed:49:59:73:6d:2b:7d:4d:02:74:f9:8f"
      
      - run:
          name: Update git profiles
          command: |
            git config push.default current
            git config user.name "CircleCI bot"
            git config user.email ${EMAIL}  

jobs:
  build:
    working_directory: .
    docker:
      - image: docker:stable

    steps:
      - run:
          name: nop
          command: echo Hei


  update_github:
    working_directory: ~/project
    docker:
      - image: alpine
    
    steps:
      - run:
          name: Install packages
          command: apk --update --no-cache add bash git curl openssh-client jq

      - checkout

      - setup_github

      - run:
          name: Check emscripten version and update
          shell: bash
          command: |
            bash docker/UpdateEmscripten.sh


  update_docker:
    working_directory: ~/project
    docker:
      - image: docker:stable
    
    steps:
      - run:
          name: Install packages
          command: apk --update --no-cache add bash git curl openssh-client jq
      
      - checkout

      - setup_remote_docker

      - setup_github

      - run:
          name: Check docker version and update
          shell: bash
          command: |
            bash docker/UpdateDockerHub.sh

workflows:
  version: 2

  build:
    jobs:
      - build

  daily_update:
    triggers:
      - schedule:
          # START UTC 21:00(JST 6:00)
          cron: "0 21 * * *"
          filters:
            branches:
              only: master
    jobs:
      - update_github
      # - update_docker
