name: C/C++ CI for Web

on: [ push ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Compiler (Latest)
        if: ${{ !contains(github.ref, 'tags/') }}
        uses: docker/build-push-action@v2
        with:
          push: ${{ contains(github.ref_name, 'master') }}
          tags: nokotan/emscripten-compiler:latest

      - name: Build Compiler (Tagged)
        if: ${{ contains(github.ref, 'tags/') }}
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: nokotan/emscripten-compiler:${{ github.ref_name }}

      - name: Build App
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./app/
          tags: nokotan/emscripten-compiler-server:latest
